### ISSUE TITLE
How to handle query parameters?

### ISSUE THREAD

**Issue by sherry-ummen** [bradyholt/aspnet-core-react-template#14]
Hi,

Wanted to know how to handle query parameters?

**Comment by bradyholt** [comment]
This project is using Entity Framework Core, so the queries are being generated automatically and any lambda expression parameters are included in the generated queries.  So, this line: https://github.com/bradyholt/aspnet-core-react-template/blob/master/api/Controllers/ContactController.cs#L41 causes the generated SQL include the lastName parameter `WHERE` conditions.

If you are wanting to know about using raw queries and passing parameters, you should take a look at the [Raw SQL Queries](https://docs.microsoft.com/en-us/ef/core/querying/raw-sql#passing-parameters) docs.

**Comment by sherry-ummen** [comment]
Stupid of me I was not clear. I meant URL query parameters.
