### ISSUE TITLE
Windows immediate session expired

### ISSUE THREAD

**Issue by balinabbb** [bradyholt/aspnet-core-react-template#16]
Hi!

I can successfully build and run this project, but I can't log in. Even if I create a new user, or use the test user hardcoded, immediately after I login I'm returned to the login screen with ?expired=1.

> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 POST http://127.0.0.1:5000/api/auth/login application/x-www-form-urlencoded 62
info: aspnetCoreReactTemplate.SpaFallbackMiddleware[0]
      Handling request: /api/auth/login
info: AspNet.Security.OAuth.Validation.OAuthValidationMiddleware[7]
      Bearer was not authenticated. Failure message: Authentication failed because the access token was invalid.
info: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerMiddleware[7]
      Bearer was not authenticated. Failure message: No SecurityTokenValidator available for token: null
info: AspNet.Security.OpenIdConnect.Server.OpenIdConnectServerMiddleware[0]
      The token request was successfully extracted from the HTTP request: {
        "username": "asdf@asdf.asdf",
        "password": "[removed for security reasons]",
        "grant_type": "password"
      }.
dbug: OpenIddict.OpenIddictProvider[0]
      The token request validation process was partially skipped because the 'client_id' parameter was missing or empty.
info: AspNet.Security.OpenIdConnect.Server.OpenIdConnectServerMiddleware[0]
      The token request was successfully validated.
dbug: AspNet.Security.OpenIdConnect.Server.OpenIdConnectServerMiddleware[0]
      The default token request handling was skipped from user code.
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Executing action method aspnetCoreReactTemplate.aspnetCoreReactTemplate.Controllers.AuthController.Login (api) with arguments ({
        "username": "asdf@asdf.asdf",
        "password": "[removed for security reasons]",
        "grant_type": "password"
      }) - ModelState is Valid
dbug: Npgsql.NpgsqlConnection[3]
      Opening connection to database 'dotnetcore' on server 'tcp://localhost:5433'.
info: Microsoft.EntityFrameworkCore.Storage.IRelationalCommandBuilderFactory[1]
      Executed DbCommand (2ms) [Parameters=[@__normalizedUserName_0='?'], CommandType='Text', CommandTimeout='30']
      SELECT "u"."Id", "u"."AccessFailedCount", "u"."ConcurrencyStamp", "u"."Email", "u"."EmailConfirmed", "u"."GivenName", "u"."LockoutEnabled", "u"."LockoutEnd", "u"."NormalizedEmail", "u"."NormalizedUserName", "u"."PasswordHash", "u"."PhoneNumber", "u"."PhoneNumberConfirmed", "u"."SecurityStamp", "u"."TwoFactorEnabled", "u"."UserName"
      FROM "AspNetUsers" AS "u"
      WHERE "u"."NormalizedUserName" = @__normalizedUserName_0
      LIMIT 1
dbug: Npgsql.NpgsqlConnection[4]
      Closing connection to database 'dotnetcore' on server 'tcp://localhost:5433'.
dbug: Npgsql.NpgsqlConnection[3]
      Opening connection to database 'dotnetcore' on server 'tcp://localhost:5433'.
info: Microsoft.EntityFrameworkCore.Storage.IRelationalCommandBuilderFactory[1]
      Executed DbCommand (1ms) [Parameters=[@__userId_0='?'], CommandType='Text', CommandTimeout='30']
      SELECT "role"."Name"
      FROM "AspNetUserRoles" AS "userRole"
      INNER JOIN "AspNetRoles" AS "role" ON "userRole"."RoleId" = "role"."Id"
      WHERE "userRole"."UserId" = @__userId_0
dbug: Npgsql.NpgsqlConnection[4]
      Closing connection to database 'dotnetcore' on server 'tcp://localhost:5433'.
dbug: Npgsql.NpgsqlConnection[3]
      Opening connection to database 'dotnetcore' on server 'tcp://localhost:5433'.
info: Microsoft.EntityFrameworkCore.Storage.IRelationalCommandBuilderFactory[1]
      Executed DbCommand (1ms) [Parameters=[@__user_Id_0='?'], CommandType='Text', CommandTimeout='30']
      SELECT "uc"."Id", "uc"."ClaimType", "uc"."ClaimValue", "uc"."UserId"
      FROM "AspNetUserClaims" AS "uc"
      WHERE "uc"."UserId" = @__user_Id_0
dbug: Npgsql.NpgsqlConnection[4]
      Closing connection to database 'dotnetcore' on server 'tcp://localhost:5433'.
info: aspnetCoreReactTemplate.aspnetCoreReactTemplate.Controllers.AuthController[0]
      User logged in (id: 246fa7f2-a0f8-422f-b806-f71749bc60e1)
info: Microsoft.AspNetCore.Mvc.SignInResult[1]
      Executing SignInResult with authentication scheme (ASOS) and the following principal: System.Security.Claims.ClaimsPrincipal.
dbug: AspNet.Security.OpenIdConnect.Server.OpenIdConnectServerMiddleware[0]
      'AspNet.Identity.SecurityStamp' was excluded from the access token claims.
dbug: AspNet.Security.OpenIdConnect.Server.OpenIdConnectServerMiddleware[0]
      'name' was excluded from the identity token claims.
dbug: AspNet.Security.OpenIdConnect.Server.OpenIdConnectServerMiddleware[0]
      'AspNet.Identity.SecurityStamp' was excluded from the identity token claims.
info: AspNet.Security.OpenIdConnect.Server.OpenIdConnectServerMiddleware[0]
      The token response was successfully returned: {
        "resource": "resource-server",
        "scope": "openid email profile roles",
        "token_type": "Bearer",
        "access_token": "[removed for security reasons]",
        "expires_in": 86400,
        "id_token": "[removed for security reasons]"
      }.
info: AspNet.Security.OpenIdConnect.Server.OpenIdConnectServerMiddleware[10]
      AuthenticationScheme: ASOS signed in.
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action aspnetCoreReactTemplate.aspnetCoreReactTemplate.Controllers.AuthController.Login (api) in 31.0254ms
info: aspnetCoreReactTemplate.SpaFallbackMiddleware[0]
      Finished handling request.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 40.3848ms 200 application/json;charset=UTF-8
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://127.0.0.1:5000/api/contacts
info: aspnetCoreReactTemplate.SpaFallbackMiddleware[0]
      Handling request: /api/contacts
info: AspNet.Security.OAuth.Validation.OAuthValidationMiddleware[7]
      Bearer was not authenticated. Failure message: Authentication failed because the access token was invalid.
info: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerMiddleware[1]
      Failed to validate the token eyJhbGciOiJSUzI1NiIsImtpZCI6IlFCU0g0M1NSUE1NTDRLQ1NaV1pBTEtLWlBTTFhLS0tJRU5ZSFQ4RUciLCJ0eXAiOiJKV1QifQ.eyJzdWIiOiIyNDZmYTdmMi1hMGY4LTQyMmYtYjgwNi1mNzE3NDliYzYwZTEiLCJuYW1lIjoiYXNkZkBhc2RmLmFzZGYiLCJ0b2tlbl91c2FnZSI6ImFjY2Vzc190b2tlbiIsImp0aSI6IjQ0ZGU1NmVkLWZmYzgtNGU5My1iOTlmLTMwNDRhN2Q3ZjRmYSIsInNjb3BlIjpbIm9wZW5pZCIsImVtYWlsIiwicHJvZmlsZSIsInJvbGVzIl0sImF1ZCI6InJlc291cmNlLXNlcnZlciIsIm5iZiI6MTUwNDg1MTE0MiwiZXhwIjoxNTA0OTM3NTQyLCJpYXQiOjE1MDQ4NTExNDIsImlzcyI6Imh0dHA6Ly8xMjcuMC4wLjE6NTAwMC8ifQ.L6D94xztoO1W_dlxahFbRtJV3qMhe87nxKpgJOyWCJhg2Vq8-mJiDOm1bc4UtrrN_ZGaVOSxpgKV3akwzrxiLJ0aRZHtDJVLWBjff5KqwEhzn_mJpqXjgyZ3QHIaMD1B1VublNTa9HwciXguazZQOvUQ8ctgvKxp8eN3k3iFEb4r3yfr_9VLfYTpymqbAKHDOH0gT-kE601CtwUdJQBnwdZNL23dODLUUVJCNaXq8qfl2nwqXlO5GLFsW0zt_omASb8VxXwmrl8wqSexjYGGK1GSGH-cyGeOhYh4eTuFPSTQy4g15h4H_AMID4ex2XIe_1O6zU8Ul0ieVD-9U8QyFQ.
Microsoft.IdentityModel.Tokens.SecurityTokenInvalidIssuerException: IDX10205: Issuer validation failed. Issuer: 'http://127.0.0.1:5000/'. Did not match: validationParameters.ValidIssuer: 'http://localhost:5000/' or validationParameters.ValidIssuers: 'null'.
   at Microsoft.IdentityModel.Tokens.Validators.ValidateIssuer(String issuer, SecurityToken securityToken, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateTokenPayload(JwtSecurityToken jwt, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.<HandleAuthenticateAsync>d__1.MoveNext()
info: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerMiddleware[7]
      Bearer was not authenticated. Failure message: IDX10205: Issuer validation failed. Issuer: 'http://127.0.0.1:5000/'. Did not match: validationParameters.ValidIssuer: 'http://localhost:5000/' or validationParameters.ValidIssuers: 'null'.
info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[2]
      Authorization failed for user: (null).
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Authorization failed for the request at filter 'Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter'.
info: Microsoft.AspNetCore.Mvc.ChallengeResult[1]
      Executing ChallengeResult with authentication schemes ().
info: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerMiddleware[12]
      AuthenticationScheme: Bearer was challenged.
info: AspNet.Security.OAuth.Validation.OAuthValidationMiddleware[12]
      AuthenticationScheme: Bearer was challenged.
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action aspnetCoreReactTemplate.Controllers.ContactsController.Get (api) in 11.5629ms
info: aspnetCoreReactTemplate.SpaFallbackMiddleware[0]
      Finished handling request.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 48.4213ms 401
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://127.0.0.1:5000/?expired=1
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 3.1883ms 200 text/html; charset=UTF-8
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://127.0.0.1:5000/main.js
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 147.1206ms 200 application/javascript; charset=UTF-8
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://127.0.0.1:5000/__webpack_hmr
info: Microsoft.AspNetCore.Server.Kestrel[14]
      Connection id "0HL7MFODCE6JA" communication error.
Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -4081 ECANCELED operation canceled
info: Microsoft.AspNetCore.Server.Kestrel[14]
      Connection id "0HL7MFODCE6JA" communication error.
Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -4081 ECANCELED operation canceled

**Comment by bradyholt** [comment]
You are certain you've tried the seeded user: user@test.com / P2ssw0rd!  ?
