### ISSUE TITLE
Build fails due to OpenIddict

### ISSUE THREAD

**Issue by cramhead** [bradyholt/aspnet-core-react-template#2]
My initial run of `npm start` failed. So I figured I'd go right into the api project, removing all node concerns and the project doesn't build. I'll spend a bit more time on it tonight, but I figured I'd let you know as it could be something really simple that you've already sorted.

`PS C:\Projects\net\aspnet-core-react-template\api> dotnet build
Project api (.NETCoreApp,Version=v1.0) will be compiled because expected outputs are missing
Compiling api for .NETCoreApp,Version=v1.0
C:\Program Files\dotnet\dotnet.exe compile-csc @C:\Projects\net\aspnet-core-react-template\api\obj\Debug\netcoreapp1.0\d
otnet-compile.rsp returned Exit Code 1
C:\Projects\net\aspnet-core-react-template\api\Models\ApplicationUser.cs(6,36): error CS0246: The type or namespace name
 'OpenIddictUser' could not be found (are you missing a using directive or an assembly reference?)
C:\Projects\net\aspnet-core-react-template\api\Models\DefaultDbContext.cs(8,18): error CS0311: The type 'vipper.Models.A
pplicationUser' cannot be used as type parameter 'TUser' in the generic type or method 'OpenIddictDbContext<TUser>'. The
re is no implicit reference conversion from 'vipper.Models.ApplicationUser' to 'Microsoft.AspNetCore.Identity.EntityFram
eworkCore.IdentityUser'.
C:\Projects\net\aspnet-core-react-template\api\Controllers\AuthController.cs(19,26): error CS0246: The type or namespace
 name 'OpenIddictUserManager<>' could not be found (are you missing a using directive or an assembly reference?)
C:\Projects\net\aspnet-core-react-template\api\Controllers\AuthController.cs(23,13): error CS0246: The type or namespace
 name 'OpenIddictUserManager<>' could not be found (are you missing a using directive or an assembly reference?)

Compilation failed.
    0 Warning(s)
    4 Error(s)

Time elapsed 00:00:00.9974886`

**Comment by bradyholt** [comment]
@cramhead Did you first run `npm install` ?  That should install node packages and also run `dotnet restore ./api && dotnet restore ./api.test`.  It looks like build is failing because OpenIddict is missing but it is specified as a dep: https://github.com/bradyholt/aspnet-core-react-template/blob/master/api/project.json#L23

**Comment by PinpointTownes** [comment]
FYI, `OpenIddictUserManager` and `OpenIddictUser` have been removed in the beta1 bits.
You can find an up-to-date tutorial [here](https://blogs.msdn.microsoft.com/webdev/2016/10/27/bearer-token-authentication-in-asp-net-core/) and a password flow sample [here](https://github.com/openiddict/openiddict-samples/tree/master/samples/PasswordFlow/AuthorizationServer).

**Comment by cramhead** [comment]
Thanks Brady. 
I did `npm install` but it initially failed as docker was down. I re-ran it and I thought that everything had gone ok. Maybe it didn't. Do you know if there is a way to run as a fresh install? I'm imagining just remove node_modules for the node portion. I ran `dotnet restore --no-cache` but it didn't store OpenIddict and the same error resulted

**Comment by bradyholt** [comment]
@cramhead Can you specify `"OpenIddict": "1.0.0-alpha2-0441"` here: https://github.com/bradyholt/aspnet-core-react-template/blob/master/api/project.json#L23 and then run `npm install` again?

**Comment by cramhead** [comment]
That work for getting the nuget package. The dotnet projects now build correctly. 
The Helloworld does present, but there is a problem finding the types. The @type/* are under node_modules as expected.

`   ERROR in [default]
   Cannot find type definition file for 'node'.

   ERROR in [default]
   Cannot find type definition file for 'react'.

   ERROR in [default]
   Cannot find type definition file for 'react-dom'.

   ERROR in [default]
   Cannot find type definition file for 'react-router'.

   ERROR in [default] C:\Projects\NET\aspnet-core-react-template\client-react\components\Landing.tsx:2:12
   Cannot find name 'require'.

   ERROR in [default] C:\Projects\NET\aspnet-core-react-template\node_modules\@types\react-router\lib\History.d.ts:2:

   Cannot find module 'history'.

   ERROR in [default] C:\Projects\NET\aspnet-core-react-template\node_modules\@types\react-router\lib\IndexRedirect.d
:3:19
   Cannot find module 'history'.

   ERROR in [default] C:\Projects\NET\aspnet-core-react-template\node_modules\@types\react-router\lib\IndexRoute.d.ts
19
   Cannot find module 'history'.

   ERROR in [default] C:\Projects\NET\aspnet-core-react-template\node_modules\@types\react-router\lib\Link.d.ts:3:19
   Cannot find module 'history'.

   ERROR in [default] C:\Projects\NET\aspnet-core-react-template\node_modules\@types\react-router\lib\Redirect.d.ts:3

   Cannot find module 'history'.

   ERROR in [default] C:\Projects\NET\aspnet-core-react-template\node_modules\@types\react-router\lib\Route.d.ts:3:25

   Cannot find module 'history'.

   ERROR in [default] C:\Projects\NET\aspnet-core-react-template\node_modules\@types\react-router\lib\Router.d.ts:6:2

   Cannot find module 'history'.

   ERROR in [default] C:\Projects\NET\aspnet-core-react-template\node_modules\@types\react-router\lib\RouterContext.d
:2:19
   Cannot find module 'history'.

   ERROR in [default] C:\Projects\NET\aspnet-core-react-template\node_modules\@types\react-router\lib\createMemoryHis
y.d.ts:1:19
   Cannot find module 'history'.

   ERROR in [default] C:\Projects\NET\aspnet-core-react-template\node_modules\@types\react-router\lib\match.d.ts:1:19

   Cannot find module 'history'.

   ERROR in [default] C:\Projects\NET\aspnet-core-react-template\node_modules\@types\react-router\lib\useRouterHistor
.ts:1:71
   Cannot find module 'history'.

   ERROR in [default] C:\Projects\NET\aspnet-core-react-template\node_modules\@types\react-router\lib\useRoutes.d.ts:
9
   Cannot find module 'history'.
   Child html-webpack-plugin for "index.html":
            Asset    Size  Chunks       Chunk Names
       index.html  574 kB       0
       chunk    {0} index.html 538 kB [rendered]
           [0] ../~/html-webpack-plugin/lib/loader.js!../client-react/index.ejs 974 bytes {0} [built]
           [1] ../~/lodash/lodash.js 537 kB {0} [built]
           [2] ../~/webpack/buildin/module.js 241 bytes {0} [built]
`
I figured problem could be because of the previous npm install failure, due to docker not being up, so  I tried wiping node_module and `npm install`. The there were no errors listed in the install, but the same errors were present. I tried modifying the tsconfig to add `typesRoot` and 'moduleResolution="node"`, but that didn't change anything.

**Comment by bradyholt** [comment]
Interesting.  What version of TypeScript do you have installed?  What does `tsc --version` output?

**Comment by cramhead** [comment]
PS C:\Projects\net\aspnet-core-react-template> tsc --version
Version 2.0.6
PS C:\Projects\net\aspnet-core-react-template> node --version
v6.9.1
PS C:\Projects\net\aspnet-core-react-template> npm --version
3.10.8

**Comment by bradyholt** [comment]
Most of these issues were specific to Windows and some were not.  When I initially setup this project I was using OSX and everything worked fine.  The following commits on master should fix all the issues on Windows.  If you pull down the latest and run `npm install && npm start` you should be good to go.

e637786040784190cadf2573b273005fd41f95bb
53c1c875ebf7f31867c7417483d89c449ad18d6b
2f46ccdf1f6ef3b083e342a3ccd97af709481d9a
b713e2b74e653ce6d024d07cab7fa25314806c5c

**Comment by cramhead** [comment]
Thanks.
I tested as well. It worked perfectly.
Marc
