### ISSUE TITLE
npm run migrate error (Mac)

### ISSUE THREAD

**Issue by muwae** [bradyholt/aspnet-core-react-template#24]
hi, i have got this error while trying to use npm run migrate on Mac, apparently the problem is related to startup.cs and program.cs, but in my research i didn't find the solution.

I have added a new model to dbcontext and ran the command.

Message:
An error occurred while calling method 'BuildWebHost' on class 'Program'. Continuing without the application service provider. Error: Parameter count mismatch.
Unable to create an object of type 'DefaultDbContext'. Add an implementation of 'IDesignTimeDbContextFactory<DefaultDbContext>' to the project, or see https://go.microsoft.com/fwlink/?linkid=851728 for additional patterns supported at design time.

**Comment by bradyholt** [comment]
Try the latest from master - this should be fixed.
