### ISSUE TITLE
Upgrade OpenIddict

### ISSUE THREAD

**Issue by bradyholt** [bradyholt/aspnet-core-react-template#3]
Project is currently using alpha version of OpenIddict and a beta version has been released.

**Comment by kikemx78** [comment]
Hi  @bradyholt , so it is not possible to run the project right now? I'm really new to asp.net and trying to set up a template but getting this error `Models/ApplicationUser.cs(6,36): error CS0246: The type or namespace name 'OpenIddictUser' could not be found (are you missing a using directive or an assembly reference?)`

Running OS

**Comment by bradyholt** [comment]
Done here: 4857c9c7559063b203b512741cb0678befd56190

**Comment by bradyholt** [comment]
@kikemx78 If you pull down the latest, things should work.

**Comment by kikemx78** [comment]
@bradyholt , Thanx a lot man. I will give it a try this week. 

:)
