### ISSUE TITLE
HMR Bundle error

### ISSUE THREAD

**Issue by SkinnnyJay** [bradyholt/aspnet-core-react-template#6]
Hello I am having an issue when running the template.
```

[HMR] bundle has 2 errors
client.js:161 ../client-react/polyfills/object-assign.ts
(4,31): error TS7006: Parameter 'target' implicitly has an 'any' type.
../client-react/polyfills/object-assign.ts
(4,39): error TS7006: Parameter 'varArgs' implicitly has an 'any' type.
```

Any Ideas?

**Comment by bradyholt** [comment]
Strange.  I did a fresh clone / `npm install && npm start` and it's working fine for me.  My guess is that maybe ts-loader is using a global version of TypeScript?  I upgraded a few dependencies and introduced a project-lock.json file for npm5.  Can you pull down latest, run `npm install` and then `npm start` and see how it goes?  If it still errors out please let me know what global version of TypeScript you have installed `tsc --version`.
