### ISSUE TITLE
Question: Can this is opened and used using Visual Studio ?

### ISSUE THREAD

**Issue by sherry-ummen** [bradyholt/aspnet-core-react-template#7]
Hi,
I work on Windows and use Visual Studio. I tried to open this folder from Visual studio, but could not get it started with Visual studio. Could you please guide me on how to use it with Visual studio. I see you use Mac so I am not sure whether you know it but still asking if you or someone else has tried to figure out.

Thanks

**Comment by bradyholt** [comment]
You could just create a new solution in Visual Studio and add the api/api.csproj and api.test/api.test.csproj projects to it and then run the api/api.csproj project.  Better yet, just use [Code](https://code.visualstudio.com/) on Windows.
