### ISSUE TITLE
Question: Where are these polyfills used?

### ISSUE THREAD

**Issue by sherry-ummen** [bradyholt/aspnet-core-react-template#8]
Hi,

I am just going through the code piece by piece to understand it. I wanted to know where is thie piece of code used and how
https://github.com/bradyholt/aspnet-core-react-template/tree/master/client-react/polyfills
Thanks

**Comment by sherry-ummen** [comment]
Also where is this file used https://github.com/bradyholt/aspnet-core-react-template/blob/master/api/Middleware/SpaFallbackMiddleware.cs ?

**Comment by sherry-ummen** [comment]
Also what is SpaFallbackMiddleware used for ? I did not understand what is its purpose.

**Comment by bradyholt** [comment]
The polyfills allow [Array.prototype.find()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find) and [Object.assign](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign) to be used in browsers that don't support them natively.  These polyfils scripts are called and initialized from here: https://github.com/bradyholt/aspnet-core-react-template/blob/master/client-react/boot.tsx#L8-L9

As for the `SpaFallbackMiddleware ` - I added a comment block just now in this commit explaining it: https://github.com/bradyholt/aspnet-core-react-template/commit/a147a374a10f01ea21e26b9768703fbff8ff3edc
